name: Publish to Registry
on:    
  push:
    tags:
      - '*'
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install dependencies
      run: npm ci

    - name: Build dependencies
      run: echo VITE_APP_VERSION=${GITHUB_REF:10} >> ./.env.production && npm run build

    - name: Inject version in front
      run: echo ${GITHUB_REF:10} && echo ${GITHUB_REF:10} > ./server/version

    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        pre: echo ::save-state name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
        name: vanessa-lanquetin/registry/dashboard
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        registry: docker.pkg.github.com
        tags: "latest,${{ env.STATE_RELEASE_VERSION }}"